// This example shows how to get an array of document elements from the document.
let document = Api.GetDocument();
let paragraph = Api.CreateParagraph();
paragraph.AddText("This paragraph is the first document element.");
document.AddElement(0, paragraph);
let tableStyle = document.CreateStyle("CustomTableStyle", "table");
tableStyle.SetBasedOn(document.GetStyle("Bordered"));
let table = Api.CreateTable(2, 2);
table.SetWidth("percent", 100);
table.SetStyle(tableStyle);
document.AddElement(1, table);
paragraph = Api.CreateParagraph();
paragraph.AddText("This table is the second document element.");
let cell = table.GetCell(0,0);
table.AddElement(cell, 0, paragraph);
let blockLvlSdt = Api.CreateBlockLvlSdt();
blockLvlSdt.GetContent().GetElement(0).AddText("This block text content control is the third document element.");
document.AddElement(2, blockLvlSdt);
let docElements = document.GetContent(false);
docElements[0].SetBold(true);
docElements[1].SetBackgroundColor(255, 111, 61, false);
docElements[2].Search("block text content control")[0].SetBold(true);