name: Build API Specification

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  build-api-spec:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Checkout repository office-js-api
        uses: actions/checkout@v4
        with:
          ref: develop
          path: office-js-api

      - name: Checkout build_tools repository
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/build_tools
          token: ${{ secrets.READ_PAT }}
          ref: master
          path: build_tools

      - name: Check release/hotfix branch for build
        run: |
          cd build_tools/scripts/sdkjs_common/jsdoc
          branch=$(python get_latest_branch.py)
          echo "Branch for build: $branch"
          echo "build_branch=$branch" >> $GITHUB_ENV

      - name: Checkout sdkjs repository
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/sdkjs
          token: ${{ secrets.READ_PAT }}
          ref: ${{ env.build_branch }}
          path: sdkjs

      - name: Checkout sdkjs-forms repository
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/sdkjs-forms
          token: ${{ secrets.READ_PAT }}
          ref: ${{ env.build_branch }}
          path: sdkjs-forms


      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate docs
        run: |
          git -C build_tools switch "$build_branch" || echo "Failed to switch $build_branch in build_tools"
          cd build_tools/scripts/sdkjs_common/jsdoc
          npm install
          python generate_docs_md.py
          python generate_docs_plugins_md.py
          cd ../../../../office-js-api

          if ! git diff --exit-code; then
            git add .
            git commit -m "Add documentation update from GitHub Actions"
            git push origin develop
          else
            echo "Nothing to commit"
          fi
