name: Update Translations

on:
  workflow_dispatch:

jobs:
  update-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Checkout office-js-api repository
        uses: actions/checkout@v4
        with:
          path: office-js-api

      - name: Checkout build_tools repository (branch)
        id: checkout_build_tools
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/build_tools
          token: ${{ secrets.READ_PAT }}
          ref: ${{ github.ref_name }}
          path: build_tools

      - name: Checkout build_tools repository (default)
        if: steps.checkout_build_tools.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/build_tools
          token: ${{ secrets.READ_PAT }}
          path: build_tools

      - name: Checkout sdkjs repository (branch)
        id: checkout_sdkjs
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/sdkjs
          token: ${{ secrets.READ_PAT }}
          ref: ${{ github.ref_name }}
          path: sdkjs

      - name: Checkout sdkjs repository (default)
        if: steps.checkout_sdkjs.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/sdkjs
          token: ${{ secrets.READ_PAT }}
          path: sdkjs

      - name: Checkout sdkjs-forms repository (branch)
        id: checkout_sdkjs_forms
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/sdkjs-forms
          token: ${{ secrets.READ_PAT }}
          ref: ${{ github.ref_name }}
          path: sdkjs-forms

      - name: Checkout sdkjs-forms repository (default)
        if: steps.checkout_sdkjs_forms.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/sdkjs-forms
          token: ${{ secrets.READ_PAT }}
          path: sdkjs-forms

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build office-js-api
        run: |
          WORKSPACE_ROOT=$(pwd)
          cd build_tools/scripts/sdkjs_common/jsdoc
          npm install
          python office-api/generate_docs_md.py --translations "$WORKSPACE_ROOT/office-js-api/Translations/Office/zh-CN.json"
          python plugins/generate_docs_methods_md.py --translations "$WORKSPACE_ROOT/office-js-api/Translations/Plugins/Methods/zh-CN.json"
          python plugins/generate_docs_events_md.py --translations "$WORKSPACE_ROOT/office-js-api/Translations/Plugins/Events/zh-CN.json"
          cd ../../../../office-js-api

          if ! git diff --exit-code; then
              git add .
              git commit -m "Update office-js-api translations from GitHub Actions"
              git push origin ${{ github.ref_name }}
            else
              echo "Nothing to commit"
            fi
